Add e2e tests
scm-manager/scm-commit-search-plugin pull request #3
Opened 2022-09-28 13:58 UTC by Pilopa

## Proposed changes

-

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

**Contributor**:
- [ ] PR is well described and the description can be used as a commit message on squash
- [ ] Related issues linked to PR if existing and labels set
- [ ] New code is covered with unit tests
- [ ] New/updated ui components are tested inside the storybook (module ui-components only) 
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [ ] Feature has been tested with different permissions
- [ ] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2022-09-28 14:07 UTC, Pilopa commented
We have to confirm that this is working correctly on a windows machine before merging.

2022-09-29 07:27 UTC, eheimbuch requested changes

2022-09-29 07:27 UTC, eheimbuch commented on src/main/js/ChangesetHitRenderer.tsx
> +      <Container className={`${repository.namespace}/${repository.name}`}>
I see what you did here. Maybe name this "id" more like a id? `search-hit-id_namespace/name`

Otherwise someone might remove this classname and break your tests.

2022-09-29 07:28 UTC, eheimbuch commented
![Screenshot from 2022-09-29 09-26-33](https://user-images.githubusercontent.com/50202942/192967640-8ae2fe8a-78d4-471e-ad45-18c6edd86deb.png)

The first test failed on first execution.

2022-09-29 07:44 UTC, eheimbuch commented
On the second run the third test failed. Seems like these tests are flaky/flappy.

2022-10-21 17:47 UTC, merged